version: '3.8'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: education
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

